[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "methods"
version = "0.0.1"
requires-python = ">=3.7"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools]
packages = ["methods"]